### ISSUE TITLE
Wrong link in library manager

### ISSUE THREAD

**Issue by OndrejPistora** [shubhamtivedi95/UltraDistSensor#1]
When i want to install your library in arduino ide > library manager and i click "more info" it will open:
https://github.cm/shubhamtrivedi95/UltraDistSensor
notice ^ cm instead com

**Comment by per1234** [comment]
The link was already corrected in https://github.com/shubhamtrivedi95/UltraDistSensor/commit/fea546bd86619f17ee40e133ff6dc24652bb6a25. However, there has not been a new release of the library since that time so this is why the fix does not appear in Library Manager.

**Comment by shubhamtrivedi95** [comment]
Thanks for bringing this issue to my notice. I will create a new release to fix this issue. Thanks again.

**Comment by shubhamtrivedi95** [comment]
I just release [a new version](https://github.com/shubhamtrivedi95/UltraDistSensor/releases/tag/1.1) of this library to fix this issue.

**Comment by per1234** [comment]
Thanks @shubhamtrivedi95! I really appreciate your attention to this matter.

As I mentioned here: https://github.com/arduino/library-registry/pull/278, we started the process of removing the library from Library Manager after concerns were raised about the previous URL potentially leading to a malicious website. We understand that there was absolutely no ill intent on your part, but still had to take action to protect the Arduino community.

We can halt that process, but only if you do one more thing, which is to delete the 1.0 tag that has the bad URL from the repository:

1. Open this page: https://github.com/shubhamtrivedi95/UltraDistSensor/releases/tag/1.0
2. Click the <kbd>Delete</kbd> button
3. Click the <kbd>Delete this tag</kbd> button

Of course, you are also welcome to use Git directly to delete the tag if you prefer, but the GitHub Web interface makes the procedure very convenient.
